export default {
  testEnvironment: "node",
  testMatch: ["<rootDir>/test/unit/**/*.test.js"],
  setupFilesAfterEnv: ["<rootDir>/test/unit/helpers/jest.setup.js"],
  clearMocks: true,
  restoreMocks: true,
  resetMocks: false,
  collectCoverageFrom: [
    "src/controllers/**/*.js",
    "src/services/**/*.js",
    "src/utils/**/*.js",
    "src/validators/**/*.js",
    "src/middlewares/auth.middlewares.js",
    "src/middlewares/error.middlewares.js",
    "src/middlewares/requestId.middleware.js",
    "!src/index.js",
    "!src/app.js",
    "!src/config/**/*.js",
    "!src/routes/**/*.js",
    "!src/models/**/*.js",
    "!src/logger/**/*.js",
    "!src/middlewares/upload.middleware.js",
    "!src/queries/**/*.js",
    "!src/constants.js",
  ],
  coverageProvider: "v8",
  coverageDirectory: "<rootDir>/tests/reports/coverage",
  coverageReporters: ["html", "lcov", "text-summary", "json-summary"],
  reporters: [
    "default",
    [
      "jest-html-reporters",
      {
        publicPath: "./tests/reports/jest/html",
        filename: "index.html",
        pageTitle: "Unit Test Report",
        expand: true,
        includeFailureMsg: true,
        includeSuiteFailure: true,
      },
    ],
  ],
};
